# Generated by Django 2.2.16 on 2020-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderGaleria',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='gal')),
            ],
        ),
    ]
