# Generated by Django 2.2.16 on 2020-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProyecto', '0002_slidergaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('nombre', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
